In [16]:
from keras.preprocessing.image import load_img, img_to_array, ImageDataGenerator
import cv2
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils

In [ ]:
# train / test 파일로 나누는 부분? 
# 현재 임의로 100 train / 20 test 로 지정했음
# 이를 랜덤으로 추출한 뒤 -> generator 에 넣을 수 있는 방법은?


In [10]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'train',
        target_size=(80, 24),
        batch_size=4,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'test',
        target_size=(80, 24),    
        batch_size=4,
        class_mode='categorical')

Found 550 images belonging to 6 classes.
Found 120 images belonging to 6 classes.


In [11]:
test_generator

In [12]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(80, 24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(6, activation='softmax'))

In [13]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:
model.fit_generator(
        train_generator,
        steps_per_epoch=20,
        epochs=50,
        validation_data=test_generator,
        validation_steps=5)

Epoch 1/50
20/20 [==============================] - 1s 31ms/step - loss: 2.0454 - accuracy: 0.1500 - val_loss: 1.8369 - val_accuracy: 0.1500
Epoch 2/50
20/20 [==============================] - 0s 24ms/step - loss: 1.7411 - accuracy: 0.2625 - val_loss: 1.6607 - val_accuracy: 0.1500
Epoch 3/50
20/20 [==============================] - 0s 25ms/step - loss: 1.6940 - accuracy: 0.3000 - val_loss: 1.6177 - val_accuracy: 0.4500
Epoch 4/50
20/20 [==============================] - 0s 25ms/step - loss: 1.5977 - accuracy: 0.3625 - val_loss: 1.3981 - val_accuracy: 0.6000
Epoch 5/50
20/20 [==============================] - 0s 25ms/step - loss: 1.5181 - accuracy: 0.4000 - val_loss: 1.3785 - val_accuracy: 0.6000
Epoch 6/50
20/20 [==============================] - 0s 24ms/step - loss: 1.2365 - accuracy: 0.5250 - val_loss: 1.0609 - val_accuracy: 0.4500
Epoch 7/50
20/20 [==============================] - 0s 25ms/step - loss: 1.1670 - accuracy: 0.5375 - val_loss: 1.2790 - val_accuracy: 0.5000
Epoch 8/50
20

In [17]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'bonghwang': 0, 'dohwa': 1, 'gongjak': 2, 'horang': 3, 'so': 4, 'yong': 5}
[[0.000 0.006 0.000 0.979 0.015 0.000]
 [1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 1.000 0.000 0.000]
 [0.003 0.286 0.003 0.685 0.001 0.021]
 [0.000 0.997 0.002 0.000 0.000 0.001]
 [0.000 0.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 1.000 0.000 0.000 0.000]
 [0.000 0.014 0.000 0.000 0.000 0.986]
 [0.000 0.998 0.000 0.000 0.000 0.002]
 [0.000 0.000 0.000 0.000 0.000 1.000]
 [0.000 0.996 0.000 0.000 0.000 0.003]
 [0.000 0.046 0.000 0.954 0.000 0.000]
 [0.025 0.000 0.974 0.000 0.000 0.000]
 [0.079 0.008 0.000 0.000 0.913 0.000]
 [0.000 0.718 0.224 0.003 0.002 0.054]
 [0.000 0.262 0.001 0.000 0.000 0.736]
 [0.000 0.000 0.998 0.000 0.002 0.000]
 [0.042 0.039 0.151 0.703 0.061 0.004]
 [0.000 0.006 0.009 0.985 0.000 0.000]
 [0.000 0.000 0.003 0.000 0.997 0.000]]


In [18]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
Instructions for updating:
Please use Model.evaluate, which supports generators.
accuracy: 85.00%


In [19]:
test_generator.class_indices

{'bonghwang': 0, 'dohwa': 1, 'gongjak': 2, 'horang': 3, 'so': 4, 'yong': 5}

In [32]:
test_generator.filenames

['bonghwang\\0109.jpeg',
 'bonghwang\\0125.jpg',
 'bonghwang\\0163.jpg',
 'bonghwang\\0210.jpg',
 'bonghwang\\0226.jpg',
 'bonghwang\\0264.jpg',
 'bonghwang\\0311.jpg',
 'bonghwang\\0327.jpg',
 'bonghwang\\0365.jpg',
 'bonghwang\\0412.jpg',
 'bonghwang\\0428.jpg',
 'bonghwang\\0466.jpg',
 'bonghwang\\0513.png',
 'bonghwang\\0529.jpg',
 'bonghwang\\0567.jpg',
 'bonghwang\\0614.jpg',
 'bonghwang\\0630.jpg',
 'bonghwang\\0668.jpg',
 'bonghwang\\0715.jpg',
 'bonghwang\\0731.jpg',
 'dohwa\\도화눈1.JPG',
 'dohwa\\도화눈10.JPG',
 'dohwa\\도화눈11.JPG',
 'dohwa\\도화눈12.JPG',
 'dohwa\\도화눈13.JPG',
 'dohwa\\도화눈14.JPG',
 'dohwa\\도화눈15.JPG',
 'dohwa\\도화눈16.JPG',
 'dohwa\\도화눈17.JPG',
 'dohwa\\도화눈18.JPG',
 'dohwa\\도화눈19.JPG',
 'dohwa\\도화눈2.JPG',
 'dohwa\\도화눈20.JPG',
 'dohwa\\도화눈3.JPG',
 'dohwa\\도화눈4.JPG',
 'dohwa\\도화눈5.JPG',
 'dohwa\\도화눈6.JPG',
 'dohwa\\도화눈7.JPG',
 'dohwa\\도화눈8.JPG',
 'dohwa\\도화눈9.JPG',
 'gongjak\\1.jpg',
 'gongjak\\10.jpg',
 'gongjak\\11.jpg',
 'gongjak\\12.jpg',
 'gongjak\\13.jpg',
 'gongjak

In [33]:
test_generator.classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
# 이미지 1개를 증식?


# 새 이미지 추가

In [20]:
np.random.seed(5)
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

In [29]:
# 왼쪽 눈
data_aug_gen = ImageDataGenerator(rescale=1./255, 
                                  rotation_range=15,
                                  width_shift_range=0.1,
                                  height_shift_range=0.1,
                                  shear_range=0.5,
                                  zoom_range=[0.8, 2.0],
                                  horizontal_flip=True,
                                  vertical_flip=True,
                                  fill_mode='nearest')


img = load_img('eyes_thresholded&auged/test2/1.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)

i = 0
for batch in data_aug_gen.flow(x, batch_size=1, save_to_dir='eyes_thresholded&auged/images', save_prefix='tri', save_format='jpg'):
    i += 1
    if i > 30: 
        break

In [31]:
#오른쪽 눈
img = load_img('eyes_thresholded&auged/test2/2.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)

i = 0
for batch in data_aug_gen.flow(x, batch_size=1, save_to_dir='eyes_thresholded&auged/images', save_prefix='tri', save_format='jpg'):
    i += 1
    if i > 30: 
        break

FileNotFoundError: [Errno 2] No such file or directory: 'eyes_thresholded&auged/test2/2.jpg'

In [43]:
test_datagen2 = ImageDataGenerator(rescale=1./255)
test_datagen2

In [44]:
test_generator2 = test_datagen2.flow_from_directory(
        'images',
        target_size=(80, 24),    
        batch_size=1,
        class_mode='categorical')

Found 1 images belonging to 1 classes.


In [45]:
print("-- Predict --")
output = model.predict_generator(test_generator2, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(train_generator.class_indices)
print(output)

-- Predict --
{'bonghwang': 0, 'dohwa': 1, 'gongjak': 2, 'horang': 3, 'so': 4, 'yong': 5}
[[0.000 0.990 0.008 0.001 0.000 0.001]]


In [46]:
for i in output:
    print(i.argmax())

1
